{{
  config(
    materialized='table'
  )
}}

SELECT 
u.USER_GUID,
u.FIRST_NAME,
u.LAST_NAME,
u.EMAIL,
u.PHONE_NUMBER,
u.CREATED_AT_UTC,
u.UPDATED_AT_UTC,
u.ADDRESS_ID,

IOA.SUM_ORDER_COST AS SUM_ORDER_COSTS,
IOA.SUM_SHIPPING_COST AS SUM_SHIPPING_COSTS,
IOA.AVG_ORDER_COST AS AVG_ORDER_COSTS,
IOA.AVG_SHIPPING_COST AS AVG_SHIPPING_COSTS,
IOA.COUNT_ORDERS AS COUNT_ORDERS,
-- IOA.FIRST_ORDER_UTC AS FIRST_ORDER_UTC,
-- IOA.LATEST_ORDER_UTC AS LATEST_ORDER_UTC,

CASE
    WHEN IOA.USER_GUID IS NOT NULL THEN TRUE ELSE FALSE END AS IS_CUSTOMER

FROM {{ ref('stg_greenery_users') }} as u
LEFT JOIN {{ ref('int_orders_agg') }} as ioa on u.user_guid = ioa.user_GUID

